spring.application.name=SpringNoSQL

# WAS Port
server.port= 11000

# MongoDB Connection
spring.mongodb.host=192.168.196.128
spring.mongodb.port=27017
spring.mongodb.database=MyDB
spring.mongodb.username=myUser
spring.mongodb.password=1234

# RedisDB Connection
spring.data.redis.host=192.168.196.128
spring.data.redis.port=6379
spring.data.redis.username=poly
spring.data.redis.password=1234


# --- Spring Cache (Redis) ---
spring.cache.type=redis
spring.cache.cache-names=melonSongs
spring.cache.redis.time-to-live=10m
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=melon
spring.cache.redis.cache-null-values=false

# (Optional) Redis connection & pool tuning
spring.data.redis.client-type=lettuce
spring.data.redis.timeout=2s
spring.data.redis.lettuce.pool.max-active=32
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.pool.max-wait=5s

# Enable cache/Redis logging to see hits and misses
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=INFO