spring.application.name=SpringNoSQL

# WAS Port
server.port= 11000

# MongoDB Connection
spring.mongodb.host=192.168.196.128
spring.mongodb.port=27017
spring.mongodb.database=MyDB
spring.mongodb.username=myUser
spring.mongodb.password=1234